name: leela_cloud_2026
description: A new Nowa project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  nowa_runtime: ^0.1.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  dio: ^5.5.0+1
  supabase_flutter: ^2.9.0
  flutter_svg: ^2.0.10
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
